services:
  dynamuszap-api:
    container_name: dynamuszap-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./tokens:/app/tokens
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    restart: unless-stopped