name: dynamuszap
services:
  dynamuszap-api:
    container_name: dynamuszap-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./tokens:/app/tokens
    env_file:
      - .env
    restart: unless-stopped
    networks:
        - default

  dynamuszap_web:
      container_name: dynamuszap_web
      image: "nginx:1.13.8-alpine"
      volumes:
        - ./:/var/www/html
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      env_file:
        - .env
      depends_on:
        - dynamuszap-api
      networks:
        - default

networks:
  default:
    name: nginx-proxy
    external: true
